'use client'

import './globals.css';
import { Inter } from 'next/font/google';
import { SessionProvider } from 'next-auth/react';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Next-Auth',
  description: 'Generated by create next app',
};

export default function RootLayout({ children, pageProps }) {
  return (
    <SessionProvider >
      <html lang="en">
        <body className="h-screen" >{children}</body>
      </html>
    </SessionProvider>
  );
}
